---
# https://github.com/ansible-collections/cisco.nxos
-   hosts: ef1-leaf-1
    gather_facts: false
    name: nxos_interfaces description
    tasks:
    -   cisco.nxos.nxos_interfaces:
            config:
            -   name: Ethernet1/11
                description: aaa
            -   name: Ethernet1/12
                description: bbb
            state: merged
        name: 'Eth1/11-12, Configure interface descriptions'
...
