- name: NDFC example playbook
  gather_facts: false
  hosts: ndfc
  tasks:
  - name: Add vrf v2
    cisco.dcnm.dcnm_vrf:
      fabric: ef1
      state: merged
      config:
      - vrf_name: v2
        vrf_id: 9000002
        vrf_template: Default_VRF_Universal
        vrf_extension_template: Default_VRF_Extension_Universal
        vlan_id: 2002
        service_vrf_template: null
        attach:
        - ip_address: 172.22.150.99
          deploy: true
  - name: Add network n2
    cisco.dcnm.dcnm_network:
      fabric: ef1
      state: merged
      config:
      - net_name: n2
        vrf_name: v2
        net_id: 2
        net_template: Default_Network_Universal
        net_extension_template: Default_Network_Extension_Universal
        vlan_id: 2
        gw_ip_subnet: '192.168.2.254/24'
        attach:
        - ip_address: 172.22.150.99
          ports: [Ethernet1/11, Ethernet1/12]
          deploy: true
