- name: NDFC example playbook
  gather_facts: false
  hosts: ndfc
  tasks:
  - name: Delete fabric ef1 vrf v2
    cisco.dcnm.dcnm_vrf:
      fabric: ef1
      state: deleted
      config:
      - vrf_name: v2
        vrf_id: 9000002
        vrf_template: Default_VRF_Universal
        vrf_extension_template: Default_VRF_Extension_Universal
        vlan_id: 2002
        service_vrf_template: null
